## NumPy Operations

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.ndim

1

In [5]:
a=np.array([(1,2,3),(4,5,6)])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.ndim

2

In [8]:
a.itemsize

4

In [9]:
a.size

6

In [10]:
a.dtype

dtype('int32')

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a.shape

(2, 3)

In [13]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [20]:
a[1]

2

In [21]:
a=np.array([(11,21,35),(14,15,16)])

In [22]:
a

array([[11, 21, 35],
       [14, 15, 16]])

In [23]:
a[1,1]

15

In [24]:
a[0,2]

35

In [25]:
a[0:,2]

array([35, 16])

In [26]:
a[1:,2]

array([16])

In [27]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
a[1:,1]

array([4, 6, 8])

In [29]:
a[0:2,1]

array([2, 4])

In [30]:
a[0:,1]

array([2, 4, 6, 8])

In [31]:
a.ndim

2

In [32]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
a.min()

1

In [35]:
a.max()

8

In [36]:
a.sum()

36

In [38]:
a.sum(axis=0)

array([16, 20])

In [39]:
a.sum(axis=1)

array([ 3,  7, 11, 15])

In [40]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [41]:
b=np.array([(1,2),(3,4),(5,6),(7,8)])

In [42]:
a+b

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [43]:
a-b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [44]:
a*b

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [45]:
a/b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
np.hstack((a,b))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6],
       [7, 8, 7, 8]])